2)Return number of employees registered for each location.

Her lokasyon için kayıtlı çalışanların sayısını döndürme

SELECT DEPARTMENTS.LOCATION_ID, COUNT(EMPLOYEES.FIRST_NAME) FROM HR.EMPLOYEES EMPLOYEES, HR.DEPARTMENTS DEPARTMENTS WHERE EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID 
GROUP BY DEPARTMENTS.LOCATION_ID